name: Code Review
permissions:
  contents: read
  pull-requests: write
on:
  pull_request:
    types: [opened, edited,closed,reopened,review_requested,ready_for_review,assigned,labeled]
  pull_request_review_comment:
    types: [created, deleted]
  issue_comment:
   types: [created, edited]

jobs:
  code-review:
    runs-on: ubuntu-latest
    if: startsWith(github.event.comment.body, 'chatgpt') || startsWith(github.event.pull_request.title, 'chatgpt') 
    steps:
    - name: ChatGPT OpenAI CodeReview
      uses: manjunathsb50/chatgpt-code-review-action@1.0.2
      with:
        PROGRAMMING_LANGUAGE: 'JavaScript'
        OPENAI_TOKEN: ${{ secrets.OPENAI_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        FULL_REVIEW_COMMENT: 'chatgpt'
        REVIEW_COMMENT_PREFIX: 'chatgpt:'
